### ISSUE TITLE
Broker should allow for rotation of the encryption key

### ISSUE THREAD

**Issue by rogeruiz** [dlapiduz/rds-broker#21]
A current limitation of the `rds-broker` is that the value for `ENC_KEY` cannot be easily rotated without going into all previously provisioned RDS instances and manually rotating the key with a new value.

## Implementation sketch

Allow for two `ENC_KEY` values such as `ENC_KEY_PREV` and `ENC_KEY` and have the app migrate between these values in the database. Then on the following deployment the `ENC_KEY_PREV` can be removed and the `ENC_KEY` remains as the default encryption key.

It's also possible that this could be a separate APP which will handles the rotation that can be deployed along side this broker as well.

## Possible limitations

The service broker would need to be unavailable during a rotation window because if any user `binds` or `unbinds` to the service, they could possibly use the updated `ENC_KEY` in the APP before the database row is migrated from the old `ENC_KEY_PREV` value.

**Comment by jmcarp** [comment]
Won't fix; prefer to put effort on brokering rds into switching to https://github.com/alphagov/paas-rds-broker.

**Comment by rogeruiz** [comment]
I'm okay with closing this then and just keep tabs on _easily rotatable v. not so easily rotatable_.
